### ISSUE TITLE
1.19.2 can't connect to server, Invalid player data

### ISSUE THREAD

**Issue by yuTwo2** [Techjar/VivecraftForgeExtensions_110#5]
Hi :)
I have the issue that I can not join my own server. I want to play with some Friends who have a VR Headset so I installed the Extension for the Mod on the Server, the only issue is that I (non VR) can not join the Server. I know that the extension is causing the error, because, without it, it works fine. The only thing that cought my eye in the server console is that the player data is invalid. If someone could help me with this, that would be great thanks :)

Here is what the Server spit out:

[11:56:53] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@36e7328f
[11:56:53] [Server thread/INFO] [minecraft/PlayerList]: einfachju logged in with entity id 280 at (-4.5, 77.0, 5.5)
[11:56:53] [Server thread/INFO] [minecraft/MinecraftServer]: einfachju joined the game
[11:56:53] [Netty Epoll Server IO #34/INFO] [Vivecraft Forge Extensions/]: Non-VR player joined: Vivecraft 1.19.2 jrbudda-NONVR-forge-0.0.14
[11:56:53] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Duplicate handler name: vr_aim_fix
Index: 3
Listeners:
0: HIGH
1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
2: NORMAL
3: ASM: com.techjar.vivecraftforge.eventhandler.EventHandlerServer@23bb6063 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
4: net.minecraftforge.eventbus.EventBus$$Lambda$4100/0x00000008015e11a0@1dab17e8
5: ASM: class com.tiviacz.travelersbackpack.handlers.ForgeEventHandler playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
6: ASM: net.minecraftforge.common.ForgeInternalHandler@68cd9a37 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
7: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
8: ASM: class net.bettercombat.forge.events.ForgeEvents onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
9: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
10: ASM: com.railwayteam.railways.Railways@1d58fec2 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
11: ASM: class com.simibubi.create.events.CommonEvents playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
12: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: Duplicate handler name: vr_aim_fix
at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055)
at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284)
at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247)
at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
at TRANSFORMER/vivecraftforgeextensions@1.3.3/com.techjar.vivecraftforge.eventhandler.EventHandlerServer.onPlayerLoggedIn(EventHandlerServer.java:220)
at TRANSFORMER/vivecraftforgeextensions@1.3.3/com.techjar.vivecraftforge.eventhandler.__EventHandlerServer_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at TRANSFORMER/forge@43.2.0/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:765)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:246)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(Connection.java:248)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
at java.base/java.lang.Thread.run(Thread.java:833)
[11:56:53] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.IllegalArgumentException: Duplicate handler name: vr_aim_fix
at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
at com.techjar.vivecraftforge.eventhandler.EventHandlerServer.onPlayerLoggedIn(EventHandlerServer.java:220) ~[VivecraftForgeExtensions-1.19.2-1.3.3.jar%23157!/:?] {re:classloading}
at com.techjar.vivecraftforge.eventhandler.__EventHandlerServer_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[VivecraftForgeExtensions-1.19.2-1.3.3.jar%23157!/:?] {re:classloading,pl:eventbus:B}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:765) ~[forge-1.19.2-43.2.0-universal.jar%23170!/:?] {re:classloading}
at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:246) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading}
at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading}
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
at java.lang.Thread.run(Thread.java:833) [?:?] {}
[11:56:54] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: einfachju lost connection: Invalid player data
[11:56:54] [Server thread/INFO] [minecraft/MinecraftServer]: einfachju left the game
[11:56:54] [Server thread/WARN] [minecraft/Connection]: handleDisconnection() called twice

**Comment by fayer3** [comment]
don't have the mod and extension on the server

**Comment by Airivol** [comment]
Having this same issue. How can this be fixed? I'm still not able to see the arms of VR players in non-vr with either vivecraft or forge extensions on the server.

**Comment by Espergium** [comment]
Do not install vivecraft AND forge extensions on the server. 

Players wanting to see VR players: Install respective VR/Non-VR. 
Server installs VFE. 
That's it.

**Comment by Airivol** [comment]
> Do not install vivecraft AND forge extensions on the server.
> 
> Players wanting to see VR players: Install respective VR/Non-VR. Server installs VFE. That's it.

Testing with [vivecraft 1.19.2-0.0.15-forge](https://www.curseforge.com/minecraft/mc-mods/vivecraft/files/4462666) on the client and [VivecraftForgeExtensions-1.19.2-1.3.3](https://www.curseforge.com/minecraft/mc-mods/vivecraft-forge-extensions/files/3949338) on the server. Still can't see arms of VR players

**Comment by fayer3** [comment]
hm, I'll check that
